version: '3'

services:
  db:
    image: mongo
    volumes:
      - ./data:/data/db
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
  place:
    build: .
    volumes:
      - .:/code
    ports:
      - 3000:3000
    depends_on:
      - db
